
valid_verbs = ["approach", "open", "go", "look", "down", "drink", "eat", "roll", "sit", "take", "throw"]

valid_nouns = ["window", "man", "door", "north", "around", "portrait", "cupboard", "down", "trapdoor", "bag", "stairs", "water", "apples", "rug", "south"]

game_states = {"in_cellar" : True, "game_won" : False, "in_kitchen": False, "in_living_room": False}

event_flags = {"key_obtained" : False, "final_key_obtained": False, "money_stash_found": False, "window_opened" : False, "rug_rolled": False}

STARTING_STATE = "in_cellar"


print ("""You are in a dark and eery cellar. You see a door that you can open to the left,
and you see a man in a cloak and hat hunched over in a corner with a magnifying glass looking
at something. You could approach him. You look around even more and notice a window. 
You could approach that too.""")

#-------------------------------------------------------------------------------

def ask_for_input():
    while True:
        ask = input(">>>>>>>>>>>>>>>>>> ")
        words = ask.split()
        if(len(words) == 0):
            print("You need to at least input something.")
        elif (words[0] in valid_verbs):
            try:
                if (words[1] in valid_nouns):
                    return (words[0], words[1])
                else: 
                    print ("I don't know the word " + words[1] + ".")
            except:
                print("That command is not long enough!")
        else:
            print ("I don't know the word " + words[0] + ".")

#-------------------------------------------------------------------------------

def run_game():
    state = STARTING_STATE
    while game_states["game_won"] == False:
        words = ask_for_input()
        if(game_states[STARTING_STATE]):
            state = in_cellar(words[0], words[1])
        elif(game_states["in_kitchen"]):
            state = in_kitchen(words[0], words[1])
        elif(game_states["in_living_room"]):
            state = in_living_room(words[0], words[1])
        elif(game_states["game_won"]):
            print("YOU WON! YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!YOU WON!")
            break
            
        process_state(state)

#-------------------------------------------------------------------------------

def in_cellar(verb, noun):
    state = "in_cellar"
    if(verb == "approach"):
        if(noun == "window"):
            print("""You approach the window and look outside. It is snowing and 
there are cop cars pisted around the house. You walk back to the center of the room.""")
        elif(noun == "man"):
            if(event_flags["key_obtained"] == False):    
                print("""You walk up to the man. He seems to be eyeing a lock on the floor. 
Man: Hello. Are you the assistant the cops gave me? I see your badge so I'm sure 
you are. Well lets test your skills shall we?
You: What skills?
man: well, the thief that stole some money stashed the money in this trapdoor right 
here, but we need the key to open it. We can't just smash it because that would 
set off the alarms the thief has placed. In order to become a brilliant detective, 
you need to obtain the bag behind this door and throw it out the window for the cops 
to retrieve. And by window I mean the one right here. Well off you go. Oh and you 
need the jey to open the door. Here, take it. 
(*You have obtained key number one*)""")
                event_flags["key_obtained"] = True
            elif(event_flags["key_obtained"] == True or event_flags["final_key_obtained"] == True):
                print("Well, what are you waiting for. You need to open the trapdoor. Its your task not mine. You're the trainee here.")
    elif(verb == "open"):
        if(noun == "window"):
            if(event_flags["window_opened"] == False):
                print("You open the window, and a cold breeze flushes your face.")
                event_flags["window_opened"] = True
            else:
                print("The window is already open")
        elif(noun == "door"):
            if(event_flags["key_obtained"] == False):
                print("You try to open the door but it is locked. You need a key to open it.")
            elif(event_flags["key_obtained"] == True):
                print("You open the door and climb the stairs. You find that you are in a kitchen. The living room is to the north.")
                state = "in_kitchen"
        elif(noun == "trapdoor"):
            if(event_flags["final_key_obtained"] == False):
                print("You need to obtain the final key in order to do this.")
            elif(event_flags["final_key_obtained"] == True):
                print("You open the trapdoor and grab the money bag. Now all you have to do is throw bag. Out the OPEN window of course.")
                event_flags["money_stash_found"] = True
    elif(verb == "look"):
        if(noun == "around"):
            print("""You are in a dark and eery cellar. You see a door that you can open to the left,
and you see a man in a cloak and hat hunched over in a corner with a magnifying glass looking
at something. You could approach him. You look around even more and notice a window. 
You could approach that too.""")
    elif(verb == "throw"):
        if(noun == "bag"):
            if(event_flags["window_opened"] == True):
                print("You throw the money bag out the open window and the cops retrieve it. Congradulations, you won the game.")
                state = "game_won"
            elif(event_flags["window_opened"] == False):
                print("Open the window...... just open it before you throw it.")

    else:
        print("You can't do that here.")
    return state

#-------------------------------------------------------------------------------

def in_kitchen(verb, noun):
    state = "in_kitchen"
    if(verb == "look"):
        if(noun == "around"):
            print("""You are in a kitchen. To the north you see a living room. 
There is a cupboard that you can open and there is also a bowl of infinate 
apples. You also see a glass of seemingly infinate water aswell. You could go 
back down to the cellar by going down stairs.""")
    elif(verb == "open"):
        if(noun == "cupboard"):
            print("You open the cupbard and see a slip of paper. It says \"roll rug\". You close the cupboard.")
    elif(verb == "down"):
        if(noun == "stairs"):
            print("You go down the stairs an find yourself back in the cellar.")
            state = "in_cellar"
    elif(verb == "drink"):
        if(noun == "water"):
            print("You drink the water, but when you put it back down it refils.")
    elif(verb == "eat"):
        if(noun == "apples"):
            print("You try to eat all the apples, but you seem to find you can't because there always seems to be more. You decie to give up.")
    elif(verb == "go"):
        if(noun == "north"):
            print("You go north and enter the living room")
            state = "in_living_room"
    else:
        print("You can't do that here.")
    return state
  
#-------------------------------------------------------------------------------
    
def in_living_room(verb, noun):
    state = "in_living_room"
    if(verb == "look"):
        if(noun == "around"):
            print("""You look around. You see the kitchen to the south. You see a 
big rug in the middle of two couches. You feel tired and think it would be nice 
to sit down. You also see a portrait that you can approach for closer inspection""")
    elif(verb == "approach"):
        if(noun == "portrait"):
            print("""You approach the portrait. You see that is is of a family. 
You also see some writing at the bottom that says \"Stop looking at the portrait and 
get on with achieving the moneybag...\". You walk back to where you were before and 
think about what to do next.""")
    elif(verb == "go"):
        if(noun == "south"):
            print("You go south and enter the kitchen")
            state = "in_kitchen"
    elif(verb == "roll"):
        if(noun == "rug"):
            if(event_flags["rug_rolled"] == False):
                print("""You roll the rung and see a key in the center. You decide to take it. Now go open the trapdoor, and take the bag.
(*You have obtained the final key*)""")
                event_flags["rug_rolled"] = True
                event_flags["final_key_obtained"] = True
            elif(event_flags["rug_rolled"] == True):
                print("You already rolled the rug. Were you not paying attention to what you were doing? Sheesh. Kids these days.")
    else:
        print("You can't do that here.")
    return state


#-------------------------------------------------------------------------------

def process_state(state):
    for item in game_states:
        game_states[item] = False
    game_states[state] = True
    
#-------------------------------------------------------------------------------    
run_game()